# Generated by Django 5.2.8 on 2025-11-20 16:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_alter_lesson_options_alter_module_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_enrollments', models.IntegerField(default=0)),
                ('active_learners', models.IntegerField(default=0)),
                ('completed_learners', models.IntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_reviews', models.IntegerField(default=0)),
                ('average_time_spent', models.IntegerField(default=0, help_text='in minutes')),
                ('completion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('engagement_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='courses.course')),
            ],
            options={
                'verbose_name': 'Course Stats',
                'verbose_name_plural': 'Course Stats',
                'db_table': 'course_stats',
            },
        ),
        migrations.CreateModel(
            name='LearningStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_study_time', models.IntegerField(default=0, help_text='in minutes')),
                ('total_lessons_completed', models.IntegerField(default=0)),
                ('total_courses_enrolled', models.IntegerField(default=0)),
                ('total_courses_completed', models.IntegerField(default=0)),
                ('total_quizzes_taken', models.IntegerField(default=0)),
                ('average_quiz_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('current_streak_days', models.IntegerField(default=0)),
                ('longest_streak_days', models.IntegerField(default=0)),
                ('last_learning_date', models.DateField(blank=True, null=True)),
                ('badges_earned', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Learning Stats',
                'verbose_name_plural': 'Learning Stats',
                'db_table': 'learning_stats',
            },
        ),
        migrations.CreateModel(
            name='UserLearningPath',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused')], default='active', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('recommended_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('courses', models.ManyToManyField(related_name='learning_paths', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_paths', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Learning Path',
                'verbose_name_plural': 'User Learning Paths',
                'db_table': 'user_learning_paths',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('user_create', 'User Created'), ('user_update', 'User Updated'), ('course_create', 'Course Created'), ('course_publish', 'Course Published'), ('enrollment', 'User Enrolled'), ('completion', 'Lesson Completed'), ('quiz_submit', 'Quiz Submitted'), ('payment', 'Payment Processed')], max_length=50)),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_id', models.UUIDField()),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='audit_logs_user_id_fbfd51_idx'), models.Index(fields=['action', 'created_at'], name='audit_logs_action_391715_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time_spent', models.IntegerField(default=0, help_text='in minutes')),
                ('lessons_completed', models.IntegerField(default=0)),
                ('quizzes_taken', models.IntegerField(default=0)),
                ('streak_preserved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Activity',
                'verbose_name_plural': 'Daily Activities',
                'db_table': 'daily_activities',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='daily_activ_user_id_28c624_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('interest', 'Matches your interests'), ('skill', 'Matches your skill level'), ('trending', 'Popular course'), ('relevant', 'Related to completed courses'), ('ai', 'AI recommended')], max_length=20)),
                ('score', models.DecimalField(decimal_places=3, max_digits=5)),
                ('clicked', models.BooleanField(default=False)),
                ('enrolled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recommendation',
                'verbose_name_plural': 'Recommendations',
                'db_table': 'recommendations',
                'ordering': ['-score'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='recommendat_user_id_f904a9_idx')],
            },
        ),
    ]
