# Generated by Django 5.2.8 on 2025-12-17 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyactivity',
            name='xp_earned',
            field=models.IntegerField(default=0, help_text='XP earned on this day'),
        ),
    ]
