# Generated by Django 5.2.8 on 2025-12-04 07:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='achievements',
            field=models.JSONField(blank=True, default=list, verbose_name='Achievements'),
        ),
        migrations.AddField(
            model_name='user',
            name='badges',
            field=models.JSONField(blank=True, default=list, verbose_name='Badges'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_activity_date',
            field=models.DateField(blank=True, null=True, verbose_name='Last Activity'),
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.IntegerField(default=1, verbose_name='Level'),
        ),
        migrations.AddField(
            model_name='user',
            name='streak',
            field=models.IntegerField(default=0, verbose_name='Current Streak'),
        ),
        migrations.AddField(
            model_name='user',
            name='xp',
            field=models.IntegerField(default=0, verbose_name='Experience Points'),
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_requests', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friend_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Дружба',
                'verbose_name_plural': 'Дружбы',
                'db_table': 'friendships',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['from_user', 'status'], name='friendships_from_us_a47fdf_idx'), models.Index(fields=['to_user', 'status'], name='friendships_to_user_607283_idx')],
                'unique_together': {('from_user', 'to_user')},
            },
        ),
    ]
