# Generated by Django 5.2.8 on 2025-12-14 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_achievements_user_badges_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='user',
            name='badges',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_activity_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='level',
        ),
        migrations.RemoveField(
            model_name='user',
            name='streak',
        ),
        migrations.RemoveField(
            model_name='user',
            name='xp',
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_language', models.CharField(default='ru', max_length=10, verbose_name='Язык')),
                ('timezone', models.CharField(default='UTC', max_length=50, verbose_name='Часовой пояс')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Email уведомления')),
                ('push_notifications', models.BooleanField(default=True, verbose_name='Push уведомления')),
                ('total_courses_completed', models.IntegerField(default=0, verbose_name='Курсов завершено')),
                ('total_learning_time', models.IntegerField(default=0, verbose_name='Время обучения (минуты)')),
                ('current_streak', models.IntegerField(default=0, verbose_name='Текущая серия (дни)')),
                ('longest_streak', models.IntegerField(default=0, verbose_name='Лучшая серия (дни)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Настройки пользователя',
                'verbose_name_plural': 'Настройки пользователей',
                'db_table': 'user_settings',
            },
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
