# Generated by Django 5.2.8 on 2025-12-18 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_achievements_remove_user_badges_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='current_streak',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='longest_streak',
        ),
    ]
