# Generated by Django 5.2.8 on 2025-12-14 19:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_is_free'),
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashcardDeck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_decks', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_decks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Flashcard Deck',
                'verbose_name_plural': 'Flashcard Decks',
                'db_table': 'flashcard_decks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('hint', models.TextField(blank=True)),
                ('easiness_factor', models.FloatField(default=2.5, validators=[django.core.validators.MinValueValidator(1.3)])),
                ('interval', models.IntegerField(default=0, help_text='Days until next review')),
                ('repetitions', models.IntegerField(default=0, help_text='Number of successful repetitions')),
                ('next_review', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_reviewed', models.DateTimeField(blank=True, null=True)),
                ('mastered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='learning.flashcarddeck')),
            ],
            options={
                'verbose_name': 'Flashcard',
                'verbose_name_plural': 'Flashcards',
                'db_table': 'flashcards',
                'ordering': ['next_review'],
            },
        ),
        migrations.AddIndex(
            model_name='flashcarddeck',
            index=models.Index(fields=['user', 'course'], name='flashcard_d_user_id_feb5c7_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['deck', 'next_review'], name='flashcards_deck_id_a3e093_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['deck', 'mastered'], name='flashcards_deck_id_e1852d_idx'),
        ),
    ]
