# Generated by Django 5.2.8 on 2025-12-14 19:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('streak', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('longest_streak', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gamification Profile',
                'verbose_name_plural': 'Gamification Profiles',
                'db_table': 'gamification_user_profiles',
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('learning', 'Learning'), ('streak', 'Streak'), ('completion', 'Completion'), ('quiz', 'Quiz'), ('special', 'Special')], default='learning', max_length=20)),
                ('icon', models.CharField(blank=True, help_text='Icon name or emoji', max_length=50)),
                ('xp_reward', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'db_table': 'user_achievements',
                'ordering': ['-earned_at'],
                'indexes': [models.Index(fields=['user', 'category'], name='user_achiev_user_id_8c1a98_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('xp_reward', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Task',
                'verbose_name_plural': 'Daily Tasks',
                'db_table': 'daily_tasks',
                'ordering': ['-date', 'completed'],
                'indexes': [models.Index(fields=['user', 'date', 'completed'], name='daily_tasks_user_id_c2a303_idx')],
                'unique_together': {('user', 'title', 'date')},
            },
        ),
        migrations.CreateModel(
            name='FocusSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('xp_earned', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False, help_text='Was session completed fully')),
                ('mode', models.CharField(choices=[('focus', 'Фокус'), ('break', 'Короткий перерыв'), ('longBreak', 'Длинный перерыв')], default='focus', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Focus Session',
                'verbose_name_plural': 'Focus Sessions',
                'db_table': 'focus_sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='focus_sessi_user_id_9c28dd_idx')],
            },
        ),
    ]
