# Generated by Django 5.2.8 on 2025-12-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='achievements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='badges',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
