# Generated by Django 5.2.8 on 2025-12-18 19:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_userprofile_achievements_userprofile_badges'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['xp'], name='idx_user_xp'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['level'], name='idx_user_level'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['last_activity_date'], name='idx_last_activity'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['-xp'], name='idx_xp_desc'),
        ),
    ]
